# Generated by Django 5.1.5 on 2025-06-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
    ]
