# Generated by Django 5.1.5 on 2025-06-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('lft', models.PositiveIntegerField(verbose_name='Left Value')),
                ('rgt', models.PositiveIntegerField(verbose_name='Right Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['lft', 'rgt'],
                'indexes': [models.Index(fields=['lft', 'rgt'], name='categories__lft_02a0b3_idx'), models.Index(fields=['parent'], name='categories__parent__91c7d9_idx')],
            },
        ),
    ]
