# Generated by Django 5.1.5 on 2025-06-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories__parent__91c7d9_idx',
        ),
    ]
