# Generated by Django 5.1.5 on 2025-06-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categorymptt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMPTT',
        ),
    ]
